apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: argoproj/argocd
  newName: kshamajain99/argocd
  newTag: v9.5.0-rc2
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
