name: Enforce Assignee

on:
  pull_request_review:
    types: [submitted]
    branches:
      - 'master'

jobs:
  enforce:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Assignee
        run: |
          export PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          export REVIEW_ID=$(jq --raw-output .review.id "$GITHUB_EVENT_PATH")
          gh api -X PUT /repos/argoproj/argo-cd/pulls/$PR_NUMBER/reviews/$REVIEW_ID/dismissals -f message='PR must be assigned first'
        env:
          GITHUB_TOKEN: ${{secrets.ARGO_BOT_TOKEN}}
